In [1]:
# importing libraries
import pandas as pd
import numpy as np

In [2]:
# read the ratings dataset
r_cols=['user_id','movie_id','rating','unix_timestamp']
ratings=pd.read_csv('ml-100k/u.data',sep='\t',names=r_cols,encoding='latin-1')

In [3]:
# Read the movie Dataset
i_cols=['movie id','movie title','release date','video release date','IMDB URL','unknown','Action','Adventure',
        'Animation','Children\'s','Comedy','Crime','Documentary','Drama','Fantasy','Film-Noir','Horror','Musical',
        'Mystery','Romance','Sci-Fi','Thriller','War','Western']
items=pd.read_csv('ml-100k/u.item',sep='|',names=i_cols,encoding='latin-1')

In [4]:
print("Ratings shape:",ratings.shape)
print("Movies shape:",items.shape)

Ratings shape: (100000, 4)
Movies shape: (1682, 24)

In [5]:
genres=['Action','Adventure','Animation','Children\'s','Comedy','Crime','Documentary',
            'Drama','Fantasy','Film-Noir','Horror','Musical','Mystery','Romance','Sci-Fi',
            'Thriller','War','Western']
print("Number of genres:",len(genres))
print("Genres:",genres)

Number of genres: 18
Genres: ['Action', 'Adventure', 'Animation', "Children's", 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']

In [6]:
genre_movie_count={}
for genre in genres:
    count=items[items[genre]==1].shape[0]
    genre_movie_count[genre]=count

In [7]:
genre_movie_count

{'Action': 251,
 'Adventure': 135,
 'Animation': 42,
 "Children's": 122,
 'Comedy': 505,
 'Crime': 109,
 'Documentary': 50,
 'Drama': 725,
 'Fantasy': 22,
 'Film-Noir': 24,
 'Horror': 92,
 'Musical': 56,
 'Mystery': 61,
 'Romance': 247,
 'Sci-Fi': 101,
 'Thriller': 251,
 'War': 71,
 'Western': 27}

In [8]:
movie_rating_count=ratings.groupby('movie_id').size()
movie_rating_count.head()

movie_id
1    452
2    131
3     90
4    209
5     86
dtype: int64

In [9]:
items['rating_count']=items['movie id'].map(movie_rating_count)
items[['movie id','movie title','rating_count']].head()

   movie id        movie title  rating_count
0         1   Toy Story (1995)           452
1         2   GoldenEye (1995)           131
2         3  Four Rooms (1995)            90
3         4  Get Shorty (1995)           209
4         5     Copycat (1995)            86

In [10]:
action_movies=items[items['Action']==1]
action_top5=action_movies.sort_values(by='rating_count',ascending=False).head(5)
action_top5[['movie id','movie title','rating_count']]

     movie id                     movie title  rating_count
49         50                Star Wars (1977)           583
180       181       Return of the Jedi (1983)           507
299       300            Air Force One (1997)           431
120       121   Independence Day (ID4) (1996)           429
173       174  Raiders of the Lost Ark (1981)           420

In [11]:
top_5_movies={}
for genre in genres:
    genre_movies=items[items[genre]==1]
    top_5=genre_movies.sort_values(by='rating_count',ascending=False).head(5)
    top_5_movies[genre]=top_5[['movie id','movie title','rating_count']]

In [12]:
top_5_movies

{'Action':      movie id                     movie title  rating_count
 49         50                Star Wars (1977)           583
 180       181       Return of the Jedi (1983)           507
 299       300            Air Force One (1997)           431
 120       121   Independence Day (ID4) (1996)           429
 173       174  Raiders of the Lost Ark (1981)           420,
 'Adventure':      movie id                      movie title  rating_count
 49         50                 Star Wars (1977)           583
 180       181        Return of the Jedi (1983)           507
 173       174   Raiders of the Lost Ark (1981)           420
 116       117                 Rock, The (1996)           378
 171       172  Empire Strikes Back, The (1980)           367,
 'Animation':      movie id                  movie title  rating_count
 0           1             Toy Story (1995)           452
 70         71        Lion King, The (1994)           220
 94         95               Aladdin (1992)           219
 587       588  Beauty and the Beast (1991)           202
 431       432              Fantasia (1940)           174,
 "Children's":      movie id                                   movie title  rating_count
 0           1                              Toy Story (1995)           452
 150       151  Willy Wonka and the Chocolate Factory (1971)           326
 422       423             E.T. the Extra-Terrestrial (1982)           300
 131       132                      Wizard of Oz, The (1939)           246
 70         71                         Lion King, The (1994)           220,
 'Comedy':      movie id                                   movie title  rating_count
 293       294                              Liar Liar (1997)           485
 0           1                              Toy Story (1995)           452
 203       204                     Back to the Future (1985)           350
 150       151  Willy Wonka and the Chocolate Factory (1971)           326
 172       173                    Princess Bride, The (1987)           324,
 'Crime':      movie id                 movie title  rating_count
 99        100                Fargo (1996)           508
 126       127       Godfather, The (1972)           413
 55         56         Pulp Fiction (1994)           394
 301       302    L.A. Confidential (1997)           297
 11         12  Usual Suspects, The (1995)           267,
 'Documentary':       movie id                   movie title  rating_count
 47          48            Hoop Dreams (1994)           117
 31          32                  Crumb (1994)            81
 812        813  Celluloid Closet, The (1995)            56
 846        847    Looking for Richard (1996)            55
 1064      1065          Koyaanisqatsi (1983)            53,
 'Drama':      movie id                  movie title  rating_count
 257       258               Contact (1997)           509
 99        100                 Fargo (1996)           508
 285       286  English Patient, The (1996)           481
 126       127        Godfather, The (1972)           413
 55         56          Pulp Fiction (1994)           394,
 'Fantasy':      movie id                        movie title  rating_count
 422       423  E.T. the Extra-Terrestrial (1982)           300
 410       411        Nutty Professor, The (1996)           163
 471       472                 Dragonheart (1996)           158
 71         72                   Mask, The (1994)           129
 754       755                     Jumanji (1995)            96,
 'Film-Noir':      movie id                       movie title  rating_count
 301       302          L.A. Confidential (1997)           297
 88         89               Blade Runner (1982)           275
 653       654                  Chinatown (1974)           147
 483       484        Maltese Falcon, The (1941)           138
 656       657  Manchurian Candidate, The (1962)           131,
 'Horror':      movie id          movie title  rating_count
 287       288        Scream (1996)           478
 182       183         Alien (1979)           291
 233       234          Jaws (1975)           280
 184       185        Psycho (1960)           239
 199       200  Shining, The (1980)           206,
 'Musical':      movie id                 movie title  rating_count
 288       289                Evita (1996)           259
 185       186  Blues Brothers, The (1980)           251
 131       132    Wizard of Oz, The (1939)           246
 142       143  Sound of Music, The (1965)           222
 70         71       Lion King, The (1994)           220,
 'Mystery':      movie id                   movie title  rating_count
 404       405    Mission: Impossible (1996)           344
 301       302      L.A. Confidential (1997)           297
 327       328      Conspiracy Theory (1997)           295
 190       191                Amadeus (1984)           276
 134       135  2001: A Space Odyssey (1968)           259,
 'Romance':      movie id                      movie title  rating_count
 49         50                 Star Wars (1977)           583
 180       181        Return of the Jedi (1983)           507
 285       286      English Patient, The (1996)           481
 236       237             Jerry Maguire (1996)           384
 171       172  Empire Strikes Back, The (1980)           367,
 'Sci-Fi':      movie id                    movie title  rating_count
 49         50               Star Wars (1977)           583
 257       258                 Contact (1997)           509
 180       181      Return of the Jedi (1983)           507
 120       121  Independence Day (ID4) (1996)           429
 6           7          Twelve Monkeys (1995)           392,
 'Thriller':      movie id                       movie title  rating_count
 99        100                      Fargo (1996)           508
 287       288                     Scream (1996)           478
 299       300              Air Force One (1997)           431
 97         98  Silence of the Lambs, The (1991)           390
 116       117                  Rock, The (1996)           378,
 'War':      movie id                      movie title  rating_count
 49         50                 Star Wars (1977)           583
 180       181        Return of the Jedi (1983)           507
 285       286      English Patient, The (1996)           481
 120       121    Independence Day (ID4) (1996)           429
 171       172  Empire Strikes Back, The (1980)           367,
 'Western':      movie id                                movie title  rating_count
 96         97                  Dances with Wolves (1990)           256
 434       435  Butch Cassidy and the Sundance Kid (1969)           216
 202       203                          Unforgiven (1992)           182
 176       177     Good, The Bad and The Ugly, The (1966)           137
 72         73                            Maverick (1994)           128}

In [13]:
action_recommendation=top_5_movies['Action']['movie title'].tolist()

In [14]:
action_recommendation

['Star Wars (1977)',
 'Return of the Jedi (1983)',
 'Air Force One (1997)',
 'Independence Day (ID4) (1996)',
 'Raiders of the Lost Ark (1981)']

In [15]:
genre_recommendations={}
for genre in genres:
    movie_list=top_5_movies[genre]['movie title'].tolist()
    genre_recommendations[genre]=movie_list

In [16]:
genre_recommendations

{'Action': ['Star Wars (1977)',
  'Return of the Jedi (1983)',
  'Air Force One (1997)',
  'Independence Day (ID4) (1996)',
  'Raiders of the Lost Ark (1981)'],
 'Adventure': ['Star Wars (1977)',
  'Return of the Jedi (1983)',
  'Raiders of the Lost Ark (1981)',
  'Rock, The (1996)',
  'Empire Strikes Back, The (1980)'],
 'Animation': ['Toy Story (1995)',
  'Lion King, The (1994)',
  'Aladdin (1992)',
  'Beauty and the Beast (1991)',
  'Fantasia (1940)'],
 "Children's": ['Toy Story (1995)',
  'Willy Wonka and the Chocolate Factory (1971)',
  'E.T. the Extra-Terrestrial (1982)',
  'Wizard of Oz, The (1939)',
  'Lion King, The (1994)'],
 'Comedy': ['Liar Liar (1997)',
  'Toy Story (1995)',
  'Back to the Future (1985)',
  'Willy Wonka and the Chocolate Factory (1971)',
  'Princess Bride, The (1987)'],
 'Crime': ['Fargo (1996)',
  'Godfather, The (1972)',
  'Pulp Fiction (1994)',
  'L.A. Confidential (1997)',
  'Usual Suspects, The (1995)'],
 'Documentary': ['Hoop Dreams (1994)',
  'Crumb (1994)',
  'Celluloid Closet, The (1995)',
  'Looking for Richard (1996)',
  'Koyaanisqatsi (1983)'],
 'Drama': ['Contact (1997)',
  'Fargo (1996)',
  'English Patient, The (1996)',
  'Godfather, The (1972)',
  'Pulp Fiction (1994)'],
 'Fantasy': ['E.T. the Extra-Terrestrial (1982)',
  'Nutty Professor, The (1996)',
  'Dragonheart (1996)',
  'Mask, The (1994)',
  'Jumanji (1995)'],
 'Film-Noir': ['L.A. Confidential (1997)',
  'Blade Runner (1982)',
  'Chinatown (1974)',
  'Maltese Falcon, The (1941)',
  'Manchurian Candidate, The (1962)'],
 'Horror': ['Scream (1996)',
  'Alien (1979)',
  'Jaws (1975)',
  'Psycho (1960)',
  'Shining, The (1980)'],
 'Musical': ['Evita (1996)',
  'Blues Brothers, The (1980)',
  'Wizard of Oz, The (1939)',
  'Sound of Music, The (1965)',
  'Lion King, The (1994)'],
 'Mystery': ['Mission: Impossible (1996)',
  'L.A. Confidential (1997)',
  'Conspiracy Theory (1997)',
  'Amadeus (1984)',
  '2001: A Space Odyssey (1968)'],
 'Romance': ['Star Wars (1977)',
  'Return of the Jedi (1983)',
  'English Patient, The (1996)',
  'Jerry Maguire (1996)',
  'Empire Strikes Back, The (1980)'],
 'Sci-Fi': ['Star Wars (1977)',
  'Contact (1997)',
  'Return of the Jedi (1983)',
  'Independence Day (ID4) (1996)',
  'Twelve Monkeys (1995)'],
 'Thriller': ['Fargo (1996)',
  'Scream (1996)',
  'Air Force One (1997)',
  'Silence of the Lambs, The (1991)',
  'Rock, The (1996)'],
 'War': ['Star Wars (1977)',
  'Return of the Jedi (1983)',
  'English Patient, The (1996)',
  'Independence Day (ID4) (1996)',
  'Empire Strikes Back, The (1980)'],
 'Western': ['Dances with Wolves (1990)',
  'Butch Cassidy and the Sundance Kid (1969)',
  'Unforgiven (1992)',
  'Good, The Bad and The Ugly, The (1966)',
  'Maverick (1994)']}

In [17]:
def popularity_based(genre,genre_recommendations):
    return genre_recommendations[genre]

In [18]:
popularity_based('Action',genre_recommendations)

['Star Wars (1977)',
 'Return of the Jedi (1983)',
 'Air Force One (1997)',
 'Independence Day (ID4) (1996)',
 'Raiders of the Lost Ark (1981)']

In [19]:
for genre,movies in genre_recommendations.items():
    print("\n", genre)
    for i,movie in enumerate(movies,1):
        print(i,movie)

 Action
1 Star Wars (1977)
2 Return of the Jedi (1983)
3 Air Force One (1997)
4 Independence Day (ID4) (1996)
5 Raiders of the Lost Ark (1981)

 Adventure
1 Star Wars (1977)
2 Return of the Jedi (1983)
3 Raiders of the Lost Ark (1981)
4 Rock, The (1996)
5 Empire Strikes Back, The (1980)

 Animation
1 Toy Story (1995)
2 Lion King, The (1994)
3 Aladdin (1992)
4 Beauty and the Beast (1991)
5 Fantasia (1940)

 Children's
1 Toy Story (1995)
2 Willy Wonka and the Chocolate Factory (1971)
3 E.T. the Extra-Terrestrial (1982)
4 Wizard of Oz, The (1939)
5 Lion King, The (1994)

 Comedy
1 Liar Liar (1997)
2 Toy Story (1995)
3 Back to the Future (1985)
4 Willy Wonka and the Chocolate Factory (1971)
5 Princess Bride, The (1987)

 Crime
1 Fargo (1996)
2 Godfather, The (1972)
3 Pulp Fiction (1994)
4 L.A. Confidential (1997)
5 Usual Suspects, The (1995)

 Documentary
1 Hoop Dreams (1994)
2 Crumb (1994)
3 Celluloid Closet, The (1995)
4 Looking for Richard (1996)
5 Koyaanisqatsi (1983)

 Drama
1 Contact (1997)
2 Fargo (1996)
3 English Patient, The (1996)
4 Godfather, The (1972)
5 Pulp Fiction (1994)

 Fantasy
1 E.T. the Extra-Terrestrial (1982)
2 Nutty Professor, The (1996)
3 Dragonheart (1996)
4 Mask, The (1994)
5 Jumanji (1995)

 Film-Noir
1 L.A. Confidential (1997)
2 Blade Runner (1982)
3 Chinatown (1974)
4 Maltese Falcon, The (1941)
5 Manchurian Candidate, The (1962)

 Horror
1 Scream (1996)
2 Alien (1979)
3 Jaws (1975)
4 Psycho (1960)
5 Shining, The (1980)

 Musical
1 Evita (1996)
2 Blues Brothers, The (1980)
3 Wizard of Oz, The (1939)
4 Sound of Music, The (1965)
5 Lion King, The (1994)

 Mystery
1 Mission: Impossible (1996)
2 L.A. Confidential (1997)
3 Conspiracy Theory (1997)
4 Amadeus (1984)
5 2001: A Space Odyssey (1968)

 Romance
1 Star Wars (1977)
2 Return of the Jedi (1983)
3 English Patient, The (1996)
4 Jerry Maguire (1996)
5 Empire Strikes Back, The (1980)

 Sci-Fi
1 Star Wars (1977)
2 Contact (1997)
3 Return of the Jedi (1983)
4 Independence Day (ID4) (1996)
5 Twelve Monkeys (1995)

 Thriller
1 Fargo (1996)
2 Scream (1996)
3 Air Force One (1997)
4 Silence of the Lambs, The (1991)
5 Rock, The (1996)

 War
1 Star Wars (1977)
2 Return of the Jedi (1983)
3 English Patient, The (1996)
4 Independence Day (ID4) (1996)
5 Empire Strikes Back, The (1980)

 Western
1 Dances with Wolves (1990)
2 Butch Cassidy and the Sundance Kid (1969)
3 Unforgiven (1992)
4 Good, The Bad and The Ugly, The (1966)
5 Maverick (1994)